const fs = require('fs');
const path = require('path');
// Prefer `expo/config-plugins`, which re-exports the exact version the host app's SDK
// ships. That resolves for a normally installed package, but not when this package is
// symlinked into an app (as the bundled example does), because Node resolves from the
// real path — which has no app node_modules above it. Fall back to the direct package,
// which this repo carries as a devDependency for exactly that case.
const { withDangerousMod } = (() => {
  try {
    return require('expo/config-plugins');
  } catch {
    return require('@expo/config-plugins');
  }
})();

const TAG = 'expo-mapbox-animated-character';

/**
 * Copies GLB models into the Android assets folder during `expo prebuild`.
 *
 * The native layer reads models with `AssetManager.open()`, which only sees files
 * under `android/app/src/main/assets`. That folder is regenerated by prebuild, so
 * dropping files in by hand does not survive `--clean`. This plugin re-copies them
 * on every prebuild instead.
 *
 * app.json:
 *   ["expo-mapbox-animated-character", { "models": ["./assets/models/fox.glb"] }]
 *
 * A model at `./assets/models/fox.glb` becomes `models/fox.glb` in the native call.
 */
function withAnimatedCharacterModels(config, props) {
  const models = (props && props.models) || [];
  const subdirectory = (props && props.subdirectory) || 'models';

  if (!Array.isArray(models)) {
    throw new Error(`[${TAG}] "models" must be an array of paths, got ${typeof models}`);
  }

  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;
      const destDir = path.join(platformProjectRoot, 'app', 'src', 'main', 'assets', subdirectory);

      if (models.length === 0) {
        console.warn(`[${TAG}] no models configured — nothing copied into Android assets.`);
        return cfg;
      }

      fs.mkdirSync(destDir, { recursive: true });

      for (const model of models) {
        const from = path.isAbsolute(model) ? model : path.resolve(projectRoot, model);
        if (!fs.existsSync(from)) {
          throw new Error(
            `[${TAG}] model not found: ${from}\n` +
              `Paths in the "models" array are resolved relative to the project root (${projectRoot}).`,
          );
        }
        const to = path.join(destDir, path.basename(from));
        fs.copyFileSync(from, to);
        console.log(`[${TAG}] ${path.basename(from)} → ${subdirectory}/${path.basename(from)}`);
      }

      return cfg;
    },
  ]);
}

module.exports = withAnimatedCharacterModels;
